#! /bin/bash
#BIND-CFG: Asistente de configuración de bind9
#Copyright (C) 2015 Ismael Milán Márquez
#Este programa es software libre: usted puede redistribuirlo y/o modificarlo bajo los términos de la Licencia Pública General GNU publicada por la Fundación para el Software Libre, ya sea la versión 3 de la Licencia, o (a su elección) cualquier versión posterior.
#Este programa se distribuye con la esperanza de que sea útil, pero SIN GARANTÍA ALGUNA; ni siquiera la garantía implícita MERCANTIL o de APTITUD PARA UN PROPÓSITO DETERMINADO. Consulte los detalles de la Licencia Pública General GNU para obtener una información más detallada. 
#Debería haber recibido una copia de la Licencia Pública General GNU junto a este programa. En caso contrario, consulte <http://www.gnu.org/licenses/>.
#Si desea contactar conmigo puede hacerlo a través de ish.professional@gmail.com o https://github.com/ishmilan

##############################################################################################################################################
##############################################################################################################################################
##############################################################################################################################################
######						┏━╸┏━┓╺┳┓╻┏━╸┏━┓	┏━┓┏━╸┏━╸┏━╸┏━┓┏━╸┏┓╻╺┳╸┏━╸	┏━┓╻  	┏┓╻┏━┓┏┳┓┏━╸╺┳┓ ┏━╸┏━┓┏┓╻┏━╸						######
######						┃  ┃ ┃ ┃┃┃┃╺┓┃ ┃	┣┳┛┣╸ ┣╸ ┣╸ ┣┳┛┣╸ ┃┗┫ ┃ ┣╸ 	┣━┫┃  	┃┗┫┣━┫┃┃┃┣╸  ┃┃ ┃  ┃ ┃┃┗┫┣╸ 						######
######						┗━╸┗━┛╺┻┛╹┗━┛┗━┛	╹┗╸┗━╸╹  ┗━╸╹┗╸┗━╸╹ ╹ ╹ ┗━╸	╹ ╹┗━╸	╹ ╹╹ ╹╹ ╹┗━╸╺┻┛╹┗━╸┗━┛╹ ╹╹  						######
##############################################################################################################################################
##############################################################################################################################################
##############################################################################################################################################
